channels:
  - conda-forge
dependencies:
  - ipython
  - pip
  - python=3.10
  - nodejs=18
  - pip:
      - aws-cdk-lib
      - awscli
      - boto3
      - git-remote-codecommit
      - python-dotenv
