# This file is sourced on every execution of zsh.
if [[ -z $HUMUS_PATH ]]; then
    export HUMUS_PATH="$HOME/.humus"
fi

export ZSH="$HUMUS_PATH/zsh/ohmyzsh"

if [[ -a "$HUMUS_PATH/zsh/zshenv_local.sh" ]]; then
    source "$HUMUS_PATH/zsh/zshenv_local.sh"
fi

export PATH="$HUMUS_PATH/vim/neovim/bin:$PATH"
