set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'elzr/vim-json'
call vundle#end()            " required
filetype plugin indent on    " required
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

map ; :
map <C-F> :FZF<CR>

nnoremap <C-E> :!%:p

set tabstop=4
set shiftwidth=4
set expandtab
set number

syntax on

set shell=/bin/zsh\ -l\ -i

" Slime
let g:slime_target = "tmux"

" Json VIM
let g:vim_json_syntax_conceal = 0

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='dark'

" Netrw
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
