version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - apt-get update && apt-get install -yq zsh
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - >
        docker build
        --build-arg ARCH=amd64
        --build-arg "BASE_IMAGE=public.ecr.aws/ubuntu/ubuntu:22.04"
        --target core
        --tag $ECR_REGISTRY/humus:main source
      - docker push $ECR_REGISTRY/humus:main
      - docker tag $ECR_REGISTRY/humus:main $ECR_REGISTRY/humus:latest
      - docker push $ECR_REGISTRY/humus:latest
      - >
        docker build
        --build-arg ARCH=amd64
        --build-arg "BASE_IMAGE=public.ecr.aws/ubuntu/ubuntu:22.04"
        --build-arg "user_id=1000"
        --build-arg "user_name=user"
        --build-arg "group_id=1000"
        --build-arg "group_name=user"
        --target user
        --tag $ECR_REGISTRY/humus:user-latest source
      - docker push $ECR_REGISTRY/humus:user-latest