version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - apt-get update && apt-get install -yq zsh
      - cdk/docker_build_push.sh
      - cdk/cdk_deploy.sh